name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: Prepare NodeJS
        uses: chrisgavin/nodejs-prepare-action@5a9adfe1877a3a3f114772464efcc7d20df36847
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build Go
        run: go build ./...
